import{S as k,i as a,a as C}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const g="/goit-js-hw-12/assets/error-74a0cd69.svg",$=document.querySelector(".gallery"),R=document.querySelector(".form");let c;function B(e){if(!e.hits.length){a.error({theme:"dark",position:"topRight",progressBarColor:"rgb(181, 27, 27)",backgroundColor:"rgb(239, 64, 64)",iconUrl:g,message:"Sorry, there are no images matching your search query. Please try again!"}),u();return}R.reset(),f(e)}function f(e){const r=e.hits.map(s=>{const{webformatURL:n,largeImageURL:t,tags:o,likes:i,views:q,comments:v,downloads:S}=s;return`<li class="gallery-item hidden">
            <a class="gallery-link" href="${t}">
              <img
                class="gallery-image"
                src="${n}"
                alt="${o}"
              />
              <div class="img-descr-container">
                <p class="img-descr-subtitle">Likes<span class="img-descr-qty">${i}</span></p>
                <p class="img-descr-subtitle">Views<span class="img-descr-qty">${q}</span></p>
                <p class="img-descr-subtitle">Comments<span class="img-descr-qty">${v}</span></p>
                <p class="img-descr-subtitle">Downloads<span class="img-descr-qty">${S}</span></p>
              </div>
            </a>
          </li>`}).join("");$.insertAdjacentHTML("beforeend",r),c?c.refresh():(c=new k(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",scrollZoom:!1}),c.on("error.simplelightbox",function(s){console.log(s)}))}const P=document.querySelector(".loader");let l=1,y=15;const h=async(e,r)=>{const{data:s}=await C.get("https://pixabay.com/api",{params:{key:"43998690-c32ec46c3205eb1d30dd41df5",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:y}});return s};async function D(e){const r=await h(e,l=1);try{const s=b(r);B(s)}catch(s){p(),a.error({theme:"dark",position:"topRight",progressBarColor:"rgb(181, 27, 27)",backgroundColor:"rgb(239, 64, 64)",iconUrl:g,message:s.message})}finally{u()}}async function M(){P.classList.add("loader-more"),l+=1,p(),L();const e=await h(d,l);try{const r=b(e);f(r),H()}catch(r){a.error({theme:"dark",position:"topRight",progressBarColor:"rgb(181, 27, 27)",backgroundColor:"rgb(239, 64, 64)",iconUrl:g,message:r.message})}finally{u()}}function b(e){if(e.totalHits===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return l>=Math.ceil(e.totalHits/y)?(p(),u(),a.info({theme:"dark",position:"topRight",backgroundColor:"rgba(38, 162, 255, 1)",message:"We're sorry, but you've reached the end of search results."}),e):(E(),e)}const O=document.querySelector(".form"),x=document.querySelector(".gallery"),w=document.querySelector(".loader"),m=document.querySelector(".btn-load");let d="";function L(){w.style.display="block"}function u(){w.style.display="none"}function E(){m.style.visibility="visible"}function p(){m.style.visibility="hidden"}async function U(e){e.preventDefault();const r=e.target;if(!r.elements.input.value.trim()){a.warning({theme:"dark",position:"topRight",message:"Input is empty",backgroundColor:"rgb(255, 150, 0)",progressBarColor:"rgb(180, 70, 0)"});return}d=r.elements.input.value.trim(),x.innerHTML="",L(),await D(d)}O.addEventListener("submit",U);m.addEventListener("click",M);function H(){let e=document.querySelector(".gallery-item"),r=e.getBoundingClientRect();e&&window.scrollBy({top:r.height*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
