import{i as a,S as k,a as C}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const g="/goit-js-hw-12/assets/error-74a0cd69.svg",$=document.querySelector(".gallery"),R=document.querySelector(".form");let c;function B(e){if(!e.hits.length){a.error({theme:"dark",position:"topRight",progressBarColor:"rgb(181, 27, 27)",backgroundColor:"rgb(239, 64, 64)",iconUrl:g,message:"Sorry, there are no images matching your search query. Please try again!"}),d();return}const t=p(e);$.insertAdjacentHTML("beforeend",t),c?c.refresh():(c=new k(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",scrollZoom:!1}),c.on("error.simplelightbox",function(s){console.log(s)})),R.reset()}function p(e){return e.hits.map(s=>{const{webformatURL:i,largeImageURL:r,tags:o,likes:n,views:q,comments:v,downloads:S}=s;return`<li class="gallery-item hidden">
            <a class="gallery-link" href="${r}">
              <img
                class="gallery-image"
                src="${i}"
                alt="${o}"
              />
              <div class="img-descr-container">
                <p class="img-descr-subtitle">Likes<span class="img-descr-qty">${n}</span></p>
                <p class="img-descr-subtitle">Views<span class="img-descr-qty">${q}</span></p>
                <p class="img-descr-subtitle">Comments<span class="img-descr-qty">${v}</span></p>
                <p class="img-descr-subtitle">Downloads<span class="img-descr-qty">${S}</span></p>
              </div>
            </a>
          </li>`}).join("")}const M=document.querySelector(".loader"),P=document.querySelector(".gallery");let l=1,y=15;const h=async(e,t)=>{const{data:s}=await C.get("https://pixabay.com/api",{params:{key:"43998690-c32ec46c3205eb1d30dd41df5",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:y}});return s};async function D(e){const t=await h(e,l=1);try{const s=b(t);B(s)}catch(s){f(),a.error({theme:"dark",position:"topRight",progressBarColor:"rgb(181, 27, 27)",backgroundColor:"rgb(239, 64, 64)",iconUrl:g,message:s.message})}finally{d()}}async function O(){M.classList.add("loader-more"),l+=1,f(),w();const e=await h(u,l);try{const t=b(e);P.insertAdjacentHTML("beforeend",p(t)),U()}catch(t){a.error({theme:"dark",position:"topRight",progressBarColor:"rgb(181, 27, 27)",backgroundColor:"rgb(239, 64, 64)",iconUrl:g,message:t.message})}finally{d()}}function b(e){if(e.totalHits===0)throw new Error("No results found");if(l>=Math.ceil(e.totalHits/y)){f(),d(),a.info({theme:"dark",position:"topRight",backgroundColor:"rgba(38, 162, 255, 1)",message:"We're sorry, but you've reached the end of search results."});return}return H(),e}const x=document.querySelector(".form"),E=document.querySelector(".gallery"),L=document.querySelector(".loader"),m=document.querySelector(".btn-load");let u="";function w(){L.style.display="block"}function d(){L.style.display="none"}function H(){m.style.visibility="visible"}function f(){m.style.visibility="hidden"}async function N(e){e.preventDefault();const t=e.target;if(!t.elements.input.value.trim()){a.warning({theme:"dark",position:"topRight",message:"Input is empty",backgroundColor:"rgb(255, 150, 0)",progressBarColor:"rgb(180, 70, 0)"});return}u=t.elements.input.value.trim(),E.innerHTML="",w(),await D(u)}x.addEventListener("submit",N);m.addEventListener("click",O);function U(){let e=document.querySelector(".gallery-item"),t=e.getBoundingClientRect();e&&window.scrollBy({top:t.height*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
