import{i as c,S as w,a as S}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const d="/goit-js-hw-12/assets/error-74a0cd69.svg",k=document.querySelector(".gallery"),C=document.querySelector(".form");let l;function $(o){if(!o.hits.length){c.error({theme:"dark",position:"topRight",progressBarColor:"rgb(181, 27, 27)",backgroundColor:"rgb(239, 64, 64)",iconUrl:d,message:"Sorry, there are no images matching your search query. Please try again!"}),g();return}const t=o.hits.map(s=>{const{webformatURL:a,largeImageURL:e,tags:r,likes:i,views:L,comments:v,downloads:q}=s;return`<li class="gallery-item hidden">
            <a class="gallery-link" href="${e}">
              <img
                class="gallery-image"
                src="${a}"
                alt="${r}"
              />
              <div class="img-descr-container">
                <p class="img-descr-subtitle">Likes<span class="img-descr-qty">${i}</span></p>
                <p class="img-descr-subtitle">Views<span class="img-descr-qty">${L}</span></p>
                <p class="img-descr-subtitle">Comments<span class="img-descr-qty">${v}</span></p>
                <p class="img-descr-subtitle">Downloads<span class="img-descr-qty">${q}</span></p>
              </div>
            </a>
          </li>`}).join("");k.insertAdjacentHTML("beforeend",t),l?l.refresh():(l=new w(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",scrollZoom:!1}),l.on("error.simplelightbox",function(s){console.log(s)})),C.reset()}let f=15;const y=async(o,t)=>{const s=await S.get("https://pixabay.com/api",{params:{key:"43998690-c32ec46c3205eb1d30dd41df5",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:f}});P(s.data)};function P(o){if(n>o.totalHits/f)b(),g(),c.error({theme:"dark",position:"topRight",progressBarColor:"rgb(181, 27, 27)",backgroundColor:"rgb(239, 64, 64)",iconUrl:d,message:"We're sorry, but you've reached the end of search results."});else try{O(),$(o)}catch(t){c.error({theme:"dark",position:"topRight",progressBarColor:"rgb(181, 27, 27)",backgroundColor:"rgb(239, 64, 64)",iconUrl:d,message:t})}finally{g()}}const R=document.querySelector(".form"),B=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".btn-load");let n=1,u="";function h(){m.style.display="block"}function g(){m.style.display="none"}function O(){p.style.visibility="visible"}function b(){p.style.visibility="hidden"}function x(o){o.preventDefault(),n=1;const t=o.target;if(!t.elements.input.value.trim()){c.warning({theme:"dark",position:"topRight",message:"Input is empty",backgroundColor:"rgb(255, 150, 0)",progressBarColor:"rgb(180, 70, 0)"});return}u=t.elements.input.value.trim(),B.innerHTML="",h(),y(u,n)}function U(){n+=1,b(),h(),y(u,n),m.classList.add("loader-more")}R.addEventListener("submit",x);p.addEventListener("click",U);
//# sourceMappingURL=commonHelpers.js.map
